-- ---------------------------------------------------------------------------
-- Boss-directed: safe cleanup of synthetic [AUTOTEST] clutter.
--
-- WHY A FUNCTION AND NOT A DELETE STATEMENT
--
-- Forensic inspection first, per the brief's §2. Four facts shaped this:
--
--   1. There are ZERO DELETE policies in the entire `maintenance` schema. No
--      client can delete anything, deliberately (append-only history, §27).
--      So cleanup can only ever run as SECURITY DEFINER.
--   2. All 21 foreign keys pointing at `cases` are NO ACTION — there is no
--      CASCADE anywhere. That is good: nothing can be wiped accidentally, but
--      every dependent row must be removed explicitly, in FK order.
--   3. `audit_log` has NO foreign key to `cases`. Deleting a case would leave
--      its audit rows dangling unless they are removed with it.
--   4. `recurrence_flags.related_case_ids` is an ARRAY of case ids, so a flag
--      belonging to case A can reference case B. That is a shared reference,
--      not an exclusive one.
--
-- ON THE APPEND-ONLY RULE
--
-- CLAUDE.md states `case_events`/`audit_log` are append-only and business
-- history is never deleted. That rule protects BUSINESS history. This database
-- contains none: a live count found 9,214 cases of which 9,214 carry the
-- `[AUTOTEST` prefix generated by `tests/helpers.ts` / `e2e/helpers.ts`, and
-- ZERO do not. Deleting a synthetic test fixture is not rewriting business
-- history — but rather than rely on that reasoning holding in future, this
-- function is built so it CANNOT touch a non-synthetic case even if someone
-- passes one in. The safety lives in the code, not in the caller's care.
--
-- WHAT IT REFUSES (all-or-nothing; the whole call raises and rolls back)
--   * any id whose symptom does not start with '[AUTOTEST'
--   * any case still referenced by a `pm_instances` row — a PM instance
--     belongs to its PM PLAN, not exclusively to the case, so removing the
--     case would destroy a record that is not the case's to destroy
--   * any case named as the primary of a duplicate that is NOT in the batch
--   * any case referenced by a surviving `recurrence_flags.related_case_ids`
-- ---------------------------------------------------------------------------

create or replace function maintenance.cleanup_synthetic_cases(p_case_ids uuid[])
returns jsonb
language plpgsql
security definer
set search_path = maintenance, public
as $$
declare
  v_total int := coalesce(array_length(p_case_ids, 1), 0);
  v_found int;
  v_bad int;
  v_deleted int;
begin
  if v_total = 0 then
    return jsonb_build_object('deleted', 0, 'note', 'empty input');
  end if;

  -- (1) every id must exist. A missing id is not silently skipped: a caller
  -- that thinks it is deleting something it is not has a bug worth surfacing.
  -- (Re-running the SAME batch after success is handled by the caller passing
  -- only ids it just read; see the idempotency test.)
  select count(*) into v_found from maintenance.cases where id = any(p_case_ids);
  if v_found <> v_total then
    raise exception 'CLEANUP_REFUSED: % of % ids do not exist — refusing a partial batch rather than guessing', v_total - v_found, v_total;
  end if;

  -- (2) provably synthetic, prefix-anchored. `like '%[AUTOTEST%'` would match
  -- a real symptom that merely mentions the word; the prefix is what the test
  -- helpers actually generate.
  select count(*) into v_bad from maintenance.cases
   where id = any(p_case_ids) and symptom not like '[AUTOTEST%';
  if v_bad > 0 then
    raise exception 'CLEANUP_REFUSED: % case(s) are not provably synthetic — a case is deletable only if repository test code is proven to have created it', v_bad;
  end if;

  -- (3) a PM instance belongs to its plan, not exclusively to the case.
  select count(*) into v_bad from maintenance.pm_instances
   where case_id = any(p_case_ids);
  if v_bad > 0 then
    raise exception 'CLEANUP_REFUSED: % case(s) are referenced by pm_instances — that row is not exclusively theirs', v_bad;
  end if;

  -- (4) never orphan a duplicate that is staying behind.
  select count(*) into v_bad from maintenance.cases
   where duplicate_of_case_id = any(p_case_ids) and not (id = any(p_case_ids));
  if v_bad > 0 then
    raise exception 'CLEANUP_REFUSED: % case(s) are the primary of a duplicate outside this batch', v_bad;
  end if;

  -- (5) never leave a surviving recurrence flag pointing at a deleted case.
  select count(*) into v_bad from maintenance.recurrence_flags f
   where not (f.case_id = any(p_case_ids))
     and exists (select 1 from unnest(f.related_case_ids) rc where rc = any(p_case_ids));
  if v_bad > 0 then
    raise exception 'CLEANUP_REFUSED: % surviving recurrence flag(s) reference a case in this batch', v_bad;
  end if;

  -- Children first, in FK order. spare_usage before spare_requests and
  -- interventions; production_boundary_events before safety_stops;
  -- capa_links before recurrence_flags.
  delete from maintenance.notifications              where case_id = any(p_case_ids);
  delete from maintenance.observations               where case_id = any(p_case_ids);
  delete from maintenance.spare_usage                where case_id = any(p_case_ids);
  delete from maintenance.spare_requests             where case_id = any(p_case_ids);
  delete from maintenance.interventions              where case_id = any(p_case_ids);
  delete from maintenance.restorations               where case_id = any(p_case_ids);
  delete from maintenance.waits                      where case_id = any(p_case_ids);
  delete from maintenance.clearances                 where case_id = any(p_case_ids);
  delete from maintenance.case_assignments           where case_id = any(p_case_ids);
  delete from maintenance.case_ownership             where case_id = any(p_case_ids);
  delete from maintenance.case_assets                where case_id = any(p_case_ids);
  delete from maintenance.case_impact_records        where case_id = any(p_case_ids);
  delete from maintenance.case_root_causes           where case_id = any(p_case_ids);
  delete from maintenance.evidence                   where case_id = any(p_case_ids);
  delete from maintenance.production_boundary_events where case_id = any(p_case_ids);
  delete from maintenance.safety_stops               where case_id = any(p_case_ids);
  delete from maintenance.capa_links                 where case_id = any(p_case_ids);
  delete from maintenance.recurrence_flags           where case_id = any(p_case_ids);
  delete from maintenance.case_events                where case_id = any(p_case_ids);
  delete from maintenance.idempotency_keys           where case_id = any(p_case_ids);

  -- audit_log has no FK, so these would otherwise dangle. Only rows whose
  -- target IS the case are removed — provably exclusive to it. Audit rows
  -- about other targets are left alone.
  delete from maintenance.audit_log
   where target_table = 'maintenance.cases' and target_id = any(p_case_ids);

  -- duplicates before their primaries, both inside the batch.
  delete from maintenance.cases
   where id = any(p_case_ids) and duplicate_of_case_id is not null;
  delete from maintenance.cases where id = any(p_case_ids);
  get diagnostics v_deleted = row_count;

  return jsonb_build_object('requested', v_total, 'deleted_cases', v_deleted);
end;
$$;

comment on function maintenance.cleanup_synthetic_cases(uuid[]) is
  'Removes VERIFIED synthetic [AUTOTEST] cases and only their exclusive dependent rows. Refuses, all-or-nothing, any case that is not prefix-proven synthetic, is referenced by a pm_instance, is the primary of a duplicate outside the batch, or is referenced by a surviving recurrence flag. Never callable by a client: EXECUTE is revoked below.';

-- Same posture as run_pm_scan / run_recurrence_scan: not reachable by any
-- signed-in client. Cleanup is an administrative act, not a user action.
revoke all on function maintenance.cleanup_synthetic_cases(uuid[]) from public;
revoke all on function maintenance.cleanup_synthetic_cases(uuid[]) from anon;
revoke all on function maintenance.cleanup_synthetic_cases(uuid[]) from authenticated;
